apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: portfolio
build:
  artifacts:
  - image: sysopsdev/portfolio
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - kubernetes/deployment.yml
    - kubernetes/service.yml
