apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      name: portfolio
  template:
    metadata:
      labels:
        name: portfolio
    spec:
      containers:
      - name: portfolio
        image: sysopsdev/portfolio
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5000
